### ISSUE TITLE
drop dependency on HaXml (replace with xml-hamlet/conduit)

### ISSUE THREAD

**Issue by jwaldmann** [jwaldmann/haskell-tpdb#21]
HaXml-1.25.4 (current) does no work with ghc-8.4.2
```
src/Text/XML/HaXml/DtdToHaskell/TypeDef.hs:79:5: error:
    Precedence parsing error
        cannot mix ‘<+>’ [infixl 6] and ‘Prelude.<>’ [infixr 6] in the same infix expression
   |
79 |     text "data" <+> nme <+> text "=" <+> nme <+> text "\t\t" <> derives
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
so we might consider dropping it altogether
